services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    depends_on:
      - php
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - NGINX_AUTORELOAD= #optional
      - NGINX_AUTORELOAD_WATCHLIST= #optional
    volumes:
      - ./config:/config
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.hosting.tls.certresolver=cf"
      - "traefik.http.routers.hosting.tls.domains[0].main=minersonline.uk"
      - "traefik.http.routers.hosting.tls.domains[0].sans=*.minersonline.uk"

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped

networks:
  proxy:
    external: true